# Generated by Django 3.0.5 on 2020-06-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
